### PR TITLE
Pull Request - onBalloonClose

### PR DESCRIPTION
**Pull request by frankiesardo**
Hi jgilfelt,
It's my first time sending a pull request, so I'm not 100% sure that I did everything right.
I modified a couple of things in your BallonItemizedOverlay because I'm using it, and while extended, I felt the need of another method, "onBallonClose", which I think It may be useful to others.

So what I did, was:

Added method onBallonClose
Modified method onBalloonOpen for better consistency

Hope you liked it.

### CODE REVIEW

**Comment by navarr** [comment]
In the future, you should make a feature branch with the changes you want to be pulled upstream.

As it is now, any modifications you make to the master branch will be added to this pull request. (Which is generally undesirable behavior).

I do however hope this gets added - it's a much needed feature.

**Comment by jgilfelt** [comment]
Unlike onBalloonOpen, your onBalloonClose event does not fire when another item in the same overlay is tapped/focused. Is this a deliberate choice?

**Comment by frankiesardo** [comment]
For me was enough to know when a user tap the X to dismiss a balloon, but we can rework the functionality if you'd like.

**Comment by jgilfelt** [comment]
I think there must be a close event corresponding to each open event, even though it may be implicit. Perhaps the caller would also like to know if it was a manual close (tap X)?

I will probably merge your change then make these few amendments when I find the time. It is a useful and much needed feature and I appreciate the contribution.

**Pull request closed without merging**
